import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { fonts } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.monserrat.variable}>
      <head>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/pokemon-ball.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/pokemon-ball.png"
        />
      </head>
      <body className={inter.className}>
        {" "}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
